[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"

[[constraint]]
  branch = "v2"
  name = "git.asafniv.me/blzit420/telebot.v2"

[prune]
  go-tests = true
  unused-packages = true
