[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/sonyarouje/simdb"

[[constraint]]
  name = "google.golang.org/api"
  version = "0.6.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/tucnak/telebot.v2"

[prune]
  go-tests = true
  unused-packages = true
